version: '3'
services:
  localstack:
    container_name: aws-localstack
    build: .
    volumes:
      - ./docker-entrypoint-aws.sh:/docker-entrypoint-initaws.d/docker-entrypoint-aws.sh
    ports:
      - '4576:4576'
      - '8080:8080'
    env_file:
      - .env
